Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -64,21 +64,20 @@ jobs:
 #        [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
 #        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
 #    
-
-     - name: Build firmware
-       run: |
-         cp build.config padavan-ng/trunk/.config
+    - name: Build firmware
+      run: |
+        cp build.config padavan-ng/trunk/.config
     
-         # Модифицируем конфиг ядра, меняя размер RAM с 64M на 128M
-         sed -i 's/mem=64M/mem=128M/g' padavan-ng/trunk/configs/boards/nexx/wt3020/kernel-3.4.x.config
+        # Модифицируем конфиг ядра, меняя размер RAM с 64M на 128M
+        sed -i 's/mem=64M/mem=128M/g' padavan-ng/trunk/configs/boards/nexx/wt3020/kernel-3.4.x.config
     
-         cd padavan-ng/trunk
-         ./clear_tree.sh
-         ./build_firmware.sh
+        cd padavan-ng/trunk
+        ./clear_tree.sh
+        ./build_firmware.sh
     
-         FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
-         [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
-         echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
+        FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
+        [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
+        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
 
 
     - name: Run custom post-build script
